// Code generated for inventory service
// © Starship 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexander-kartavtsev/starship/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *InventoryRepository) Get(_a0 context.Context, _a1 string) (model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InventoryRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *InventoryRepository_Expecter) Get(_a0 interface{}, _a1 interface{}) *InventoryRepository_Get_Call {
	return &InventoryRepository_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *InventoryRepository_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *InventoryRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_Get_Call) Return(_a0 model.Part, _a1 error) *InventoryRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *InventoryRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InitFull provides a mock function with given fields: ctx
func (_m *InventoryRepository) InitFull(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitFull")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_InitFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitFull'
type InventoryRepository_InitFull_Call struct {
	*mock.Call
}

// InitFull is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InventoryRepository_Expecter) InitFull(ctx interface{}) *InventoryRepository_InitFull_Call {
	return &InventoryRepository_InitFull_Call{Call: _e.mock.On("InitFull", ctx)}
}

func (_c *InventoryRepository_InitFull_Call) Run(run func(ctx context.Context)) *InventoryRepository_InitFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InventoryRepository_InitFull_Call) Return(_a0 error) *InventoryRepository_InitFull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_InitFull_Call) RunAndReturn(run func(context.Context) error) *InventoryRepository_InitFull_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0, _a1
func (_m *InventoryRepository) List(_a0 context.Context, _a1 model.PartsFilter) (map[string]model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[string]model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) (map[string]model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) map[string]model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InventoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.PartsFilter
func (_e *InventoryRepository_Expecter) List(_a0 interface{}, _a1 interface{}) *InventoryRepository_List_Call {
	return &InventoryRepository_List_Call{Call: _e.mock.On("List", _a0, _a1)}
}

func (_c *InventoryRepository_List_Call) Run(run func(_a0 context.Context, _a1 model.PartsFilter)) *InventoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *InventoryRepository_List_Call) Return(_a0 map[string]model.Part, _a1 error) *InventoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_List_Call) RunAndReturn(run func(context.Context, model.PartsFilter) (map[string]model.Part, error)) *InventoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
