// Code generated for inventory service
// © Starship 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexander-kartavtsev/starship/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TelegramService is an autogenerated mock type for the TelegramService type
type TelegramService struct {
	mock.Mock
}

type TelegramService_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramService) EXPECT() *TelegramService_Expecter {
	return &TelegramService_Expecter{mock: &_m.Mock}
}

// SendAssembledNotification provides a mock function with given fields: ctx, event
func (_m *TelegramService) SendAssembledNotification(ctx context.Context, event model.ShipAssembledKafkaEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledKafkaEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAssembledNotification'
type TelegramService_SendAssembledNotification_Call struct {
	*mock.Call
}

// SendAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledKafkaEvent
func (_e *TelegramService_Expecter) SendAssembledNotification(ctx interface{}, event interface{}) *TelegramService_SendAssembledNotification_Call {
	return &TelegramService_SendAssembledNotification_Call{Call: _e.mock.On("SendAssembledNotification", ctx, event)}
}

func (_c *TelegramService_SendAssembledNotification_Call) Run(run func(ctx context.Context, event model.ShipAssembledKafkaEvent)) *TelegramService_SendAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledKafkaEvent))
	})
	return _c
}

func (_c *TelegramService_SendAssembledNotification_Call) Return(_a0 error) *TelegramService_SendAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendAssembledNotification_Call) RunAndReturn(run func(context.Context, model.ShipAssembledKafkaEvent) error) *TelegramService_SendAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendPaidNotification provides a mock function with given fields: ctx, event
func (_m *TelegramService) SendPaidNotification(ctx context.Context, event model.OrderKafkaEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderKafkaEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPaidNotification'
type TelegramService_SendPaidNotification_Call struct {
	*mock.Call
}

// SendPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderKafkaEvent
func (_e *TelegramService_Expecter) SendPaidNotification(ctx interface{}, event interface{}) *TelegramService_SendPaidNotification_Call {
	return &TelegramService_SendPaidNotification_Call{Call: _e.mock.On("SendPaidNotification", ctx, event)}
}

func (_c *TelegramService_SendPaidNotification_Call) Run(run func(ctx context.Context, event model.OrderKafkaEvent)) *TelegramService_SendPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderKafkaEvent))
	})
	return _c
}

func (_c *TelegramService_SendPaidNotification_Call) Return(_a0 error) *TelegramService_SendPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderKafkaEvent) error) *TelegramService_SendPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramService creates a new instance of TelegramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramService {
	mock := &TelegramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
