// Code generated for inventory service
// © Starship 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexander-kartavtsev/starship/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ProducerService is an autogenerated mock type for the ProducerService type
type ProducerService struct {
	mock.Mock
}

type ProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProducerService) EXPECT() *ProducerService_Expecter {
	return &ProducerService_Expecter{mock: &_m.Mock}
}

// ProduceShipAssembled provides a mock function with given fields: ctx, event
func (_m *ProducerService) ProduceShipAssembled(ctx context.Context, event model.ShipAssembledKafkaEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceShipAssembled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledKafkaEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProducerService_ProduceShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceShipAssembled'
type ProducerService_ProduceShipAssembled_Call struct {
	*mock.Call
}

// ProduceShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledKafkaEvent
func (_e *ProducerService_Expecter) ProduceShipAssembled(ctx interface{}, event interface{}) *ProducerService_ProduceShipAssembled_Call {
	return &ProducerService_ProduceShipAssembled_Call{Call: _e.mock.On("ProduceShipAssembled", ctx, event)}
}

func (_c *ProducerService_ProduceShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledKafkaEvent)) *ProducerService_ProduceShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledKafkaEvent))
	})
	return _c
}

func (_c *ProducerService_ProduceShipAssembled_Call) Return(_a0 error) *ProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProducerService_ProduceShipAssembled_Call) RunAndReturn(run func(context.Context, model.ShipAssembledKafkaEvent) error) *ProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducerService creates a new instance of ProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerService {
	mock := &ProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
