// Code generated for inventory service
// © Starship 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/alexander-kartavtsev/starship/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *InventoryService) Get(_a0 context.Context, _a1 string) (model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InventoryService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *InventoryService_Expecter) Get(_a0 interface{}, _a1 interface{}) *InventoryService_Get_Call {
	return &InventoryService_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *InventoryService_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *InventoryService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_Get_Call) Return(_a0 model.Part, _a1 error) *InventoryService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *InventoryService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0, _a1
func (_m *InventoryService) List(_a0 context.Context, _a1 model.PartsFilter) (map[string]model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[string]model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) (map[string]model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) map[string]model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InventoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.PartsFilter
func (_e *InventoryService_Expecter) List(_a0 interface{}, _a1 interface{}) *InventoryService_List_Call {
	return &InventoryService_List_Call{Call: _e.mock.On("List", _a0, _a1)}
}

func (_c *InventoryService_List_Call) Run(run func(_a0 context.Context, _a1 model.PartsFilter)) *InventoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *InventoryService_List_Call) Return(_a0 map[string]model.Part, _a1 error) *InventoryService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_List_Call) RunAndReturn(run func(context.Context, model.PartsFilter) (map[string]model.Part, error)) *InventoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
