// Code generated for inventory service
// © Starship 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// AssemblyConsumerConfig is an autogenerated mock type for the AssemblyConsumerConfig type
type AssemblyConsumerConfig struct {
	mock.Mock
}

type AssemblyConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyConsumerConfig) EXPECT() *AssemblyConsumerConfig_Expecter {
	return &AssemblyConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *AssemblyConsumerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// AssemblyConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type AssemblyConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *AssemblyConsumerConfig_Expecter) Config() *AssemblyConsumerConfig_Config_Call {
	return &AssemblyConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *AssemblyConsumerConfig_Config_Call) Run(run func()) *AssemblyConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssemblyConsumerConfig_Config_Call) Return(_a0 *sarama.Config) *AssemblyConsumerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *AssemblyConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function with no fields
func (_m *AssemblyConsumerConfig) GroupID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AssemblyConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type AssemblyConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *AssemblyConsumerConfig_Expecter) GroupID() *AssemblyConsumerConfig_GroupID_Call {
	return &AssemblyConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *AssemblyConsumerConfig_GroupID_Call) Run(run func()) *AssemblyConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssemblyConsumerConfig_GroupID_Call) Return(_a0 string) *AssemblyConsumerConfig_GroupID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *AssemblyConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *AssemblyConsumerConfig) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AssemblyConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type AssemblyConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *AssemblyConsumerConfig_Expecter) Topic() *AssemblyConsumerConfig_Topic_Call {
	return &AssemblyConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *AssemblyConsumerConfig_Topic_Call) Run(run func()) *AssemblyConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AssemblyConsumerConfig_Topic_Call) Return(_a0 string) *AssemblyConsumerConfig_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyConsumerConfig_Topic_Call) RunAndReturn(run func() string) *AssemblyConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssemblyConsumerConfig creates a new instance of AssemblyConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyConsumerConfig {
	mock := &AssemblyConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
