// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderByIdOperation OperationName = "CancelOrderById"
	CreateOrderOperation     OperationName = "CreateOrder"
	GetOrderByUuidOperation  OperationName = "GetOrderByUuid"
	PayOrderByUuidOperation  OperationName = "PayOrderByUuid"
)
