// Code generated by ogen, DO NOT EDIT.
package order_v1

type CanselOrderByIdRes interface {
	canselOrderByIdRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderByUuidRes interface {
	getOrderByUuidRes()
}

type PayOrderByUuidRes interface {
	payOrderByUuidRes()
}
